const wishes = {
  birthday: [
    "Boldog születésnapot!",
    "Sok boldogságot!",
    "Minden álmod valóra váljon!",
    "Hosszú és boldog életet kívánok!",
    "Gyertyák fényében gazdagodjon a napod!",
    "Ünnepeld a mai napot, mint soha azelőtt!",
    "Legyen ez az év a legjobb éved!",
    "Egy évvel bölcsébb lettél, ünnepeld meg!",
    "Mai napon minden kívánságod teljesüljön!",
    "Köszöntelek ezen a csodálatos napon!",
    "További sok boldog születésnapot!",
    "Minden eddiginél jobb évet kívánok!",
    "A mai nap csak rólad szól!",
    "Csak a legjobbakat neked, ma és minden nap!",
    "Születésnapod alkalmából sok örömöt és boldogságot kívánok!",
    "Legyen ez a születésnapod különleges, mint te magad!",
    "Egy újabb évet zártál, de a legjobbak még csak most jönnek!",
    "Az élet szépségeit kívánom neked születésnapodon!",
    "Sok szeretettel gondolunk rád ezen a különleges napon!",
    "Egy újabb év, tele új reményekkel és álmokkal!",
    "Boldogságban, egészségben és szeretetben gazdag évet kívánok!",
    "Ma van az a nap, amikor duplán lehet ünnepelni: te vagy a főszereplő!",
    "Bármi legyen is a kívánságod, remélem, valóra válik!",
    "Ünnepeld a mai napot, hiszen te vagy a világ középpontja!",
    "Legyen a mai nap tele nevetéssel, örömmel és szeretettel!",
    "Az évek telnek, de te csak szebb és bölcsébb leszel!",
    "Ma minden tortaszelet egy boldog emlék legyen!",
    "A legcsodálatosabb születésnapi kívánságokat küldöm neked!",
    "Kívánom, hogy a következő év minden napja boldogsággal teli legyen!",
    "Remélem, hogy a mai nap minden pillanata boldogságot hoz!",
    "Ünnepeld nagyban, mert te is nagyszerű vagy!",
    "Legyen a születésnapod annyira csodálatos, mint te magad!",
    "Kívánom, hogy ezen a különleges napon minden, amit csak kívánsz, teljesüljön!",
    "Minden pillanatban találj örömöt, és minden órában boldogságot!",
    "A legmelegebb üdvözleteket küldöm ezen a különleges napon!",
    "További sok varázslatos és felejthetetlen születésnapot kívánok!",
    "Legyen ez a születésnap tele új reményekkel és boldog pillanatokkal!",
    "Legyen a mai nap olyan különleges, mint te!",
    "Boldog születésnapot a világ egyik legcsodálatosabb emberének!",
    "A legfényesebb mosolyokat és a legboldogabb pillanatokat kívánom neked ma!",
    "Töltsd a napodat azzal, ami boldoggá tesz, és azokkal, akiket szeretsz!",
    "Az élet egy csodálatos út, élvezd minden lépését!",
  ],
  anniversary: [
    "Boldog évfordulót!",
    "Ünnepeljétek együtt!",
    "További sok boldog közös évet!",
    "Az örök szeretet ünnepnapja ez számotokra.",
  ],
  nameDay: [
    "Boldog névnapot!",
    "Legyen szép a napod!",
    "Sok szeretettel gondolunk rád ezen a különleges napon.",
    "Minden jót kívánok ezen a szép napon.",
    "Egyedi legyen a mai nap, tele örömmel és boldogsággal!",
    "Kívánok Neked sok boldogságot és egészséget!",
    "A legjobbakat kívánom ebben az évben!",
    "Egy csokorral tele virággal kívánok boldog névnapot!",
    "Mai napra csak a legfinomabb tortát kívánom!",
    "Az élet legnagyobb örömei és sikerei várnak rád!",
    "Egészség, boldogság, szeretet kísérjen minden napodon!",
    "Legyen ez a nap csak Rólad szóló ünneplés!",
    "Minden vágyad teljesüljön ezen a különleges napon!",
    "Legyen a mai nap tele meglepetésekkel és örömökkel!",
    "A csillagok világítsanak utadon ezen a különleges napon!",
    "Szeretettel gondolok Rád és kívánok boldog névnapot!",
    "Küldök egy virtuális ölelést ezen a különleges napon!",
    "Az élet minden szépségével és örömével kísérjen téged!",
    "Kívánok egy életre szóló boldogságot és szeretetet!",
    "Legyen ma minden pillanatod tele nevetéssel és boldogsággal!",
  ],
  illness: [
    "Mihamarabbi gyógyulást!",
    "Egészséget és erőt kívánok!",
    "Tarts ki! Hamarosan jobban leszel.",
    "Jobbulást kívánok neked!",
    "Gyors felépülést kívánok!",
    "Minden nap egy lépés a jobb felé. Gyógyulj meg hamar!",
    "Küldök egy nagy adag pozitív energiát a gyors gyógyulásért!",
    "Remélem, hogy minden nap egyre jobban érzed magad!",
    "Kívánom, hogy minél hamarabb visszanyerd az egészségedet!",
    "Legyél erős, a gyógyulás már úton van feléd!",
    "Fogadd szeretetem és gondoskodásom, amíg felépülsz.",
    "Sok pihenést és gyors gyógyulást kívánok!",
    "A legjobbakat kívánom Neked ebben a nehéz időszakban.",
    "Mindenkinek szüksége van egy kis pihenőre. Gyógyulj meg hamar!",
    "Remélem, hogy az üzenetem egy mosolyt csal az arcodra és segít a gyógyulásban.",
    "Tartsd magad pozitívan, és hamarosan jobban leszel!",
    "Küldök neked erőt és bátorságot a gyógyuláshoz.",
    "Minden gondolatommal Veled vagyok ebben a nehéz időszakban.",
    "Ne feledd, nem vagy egyedül. Melletted állunk a gyógyulásod során.",
    "Egy kis türelem, és minden rendben lesz. Jobbulást!",
  ],
  breakup: [
    "Tartsd magad erősnek!",
    "Egy ajtó bezárul, egy másik kinyílik.",
    "Idővel minden seb begyógyul.",
  ],
  congratulations: [
    "Gratulálok a sikeredhez!",
    "Fantasztikus teljesítmény, büszkék vagyunk rád!",
    "További sok sikert kívánunk!",
  ],
  christmas: [
    "Boldog karácsonyt!",
    "Békés, boldog ünnepeket kívánok!",
    "Szeretettel teli karácsonyt!",
  ],
  newYear: [
    "Boldog új évet!",
    "Sok sikert és boldogságot az új évben!",
    "Az új év hozzon megvalósult álmokat!",
  ],
  graduation: [
    "Gratulálok a diploma megszerzéséhez!",
    "A kemény munka meghozta gyümölcsét, gratulálok!",
    "Új fejezet kezdődik, sok sikert!",
  ],
  newJob: [
    "Gratulálok az új álláshoz!",
    "Sok sikert az új kihívásokhoz!",
    "Biztos vagyok benne, hogy nagyszerű munkát végzel!",
  ],
};

export default wishes;
